spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?user=postgres.xmdholgnwerzedczpjum&password=lBaqpobDyQlSc1TU
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: {{GOOGLE_OAUTH_CLIENT_ID}}
            client-secret: {{GOOGLE_OAUTH_CLIENT_SECRET}}
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email
              - https://www.googleapis.com/auth/drive.file
              - https://www.googleapis.com/auth/script.projects
              - https://www.googleapis.com/auth/forms.body
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent
# ?access_type=offline&prompt=consent 부분 확인
# access_type=offline 는 구글 Refresh Token 을 사용하겠다는 의미. 최초 1회만 발급
# prompt=consent 는 계속 물어보고 발급(개발용)
aws:
  region: {{AWS_REGION}}
  dynamodb:
    table-name: {{AWS_TABLE_NAME}}
  credentials:
    access-key: {{AWS_ACCESS_KEY}}
    secret-key: {{AWS_SECRET_KEY}}

jwt:
  secret: {{JWT_SECRET}}
